# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: 
  push: 
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npm install -g typescript
    - run: tsc
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r package.zip package.json index.js dist node_modules src lib
#     - uses: hkusu/s3-upload-action@v2
#       with:
#         aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
#         aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
#         aws-region: "${{ secrets.AWS_REGION }}"
#         aws-bucket: "${{ secrets.AWS_BUCKET }}"
#         file-path: 'package.zip'
#         bucket-root: "ff-lambda"
#         destination-dir: "/"
    
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          s3-bucket: ${{ secrets.AWS_BUCKET }}
          zip_file: "package.zip"
          function_name: ffprobe
          s3-key: "ff-lambda/package.zip"
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Build"
        files: |
          *.zip
